variable "gcp_credentials" {}
variable "gcp_region" {}
variable "gcp_zone" {}
variable "gcp_project" {}
variable "cluster_name" {}
variable "initial_node_count" {}
variable "master_username" {}
variable "master_password" {}
variable "node_machine_type" {}
variable "node_disk_size" {}
variable "environment" {}
